"""init migration

Revision ID: 01b06dacf99b
Revises: b0d6f946c039
Create Date: 2019-09-17 19:36:17.714257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b06dacf99b'
down_revision = 'b0d6f946c039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like_pitch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('commenting', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('commenting', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commenting', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('commenting', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('like_pitch')
    # ### end Alembic commands ###
