"""init migration

Revision ID: 11ccca6e3da8
Revises: 721ccdc789e3
Create Date: 2019-09-17 11:53:17.334392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ccca6e3da8'
down_revision = '721ccdc789e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commenting', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('commenting_post_id_fkey', 'commenting', type_='foreignkey')
    op.create_foreign_key(None, 'commenting', 'users', ['user_id'], ['id'])
    op.drop_column('commenting', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commenting', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'commenting', type_='foreignkey')
    op.create_foreign_key('commenting_post_id_fkey', 'commenting', 'post', ['post_id'], ['id'])
    op.drop_column('commenting', 'user_id')
    # ### end Alembic commands ###
