"""init migration

Revision ID: 515d89cc2c6d
Revises: fd2194ecea90
Create Date: 2019-09-17 12:29:18.992463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515d89cc2c6d'
down_revision = 'fd2194ecea90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('commenting_user_id_fkey', 'commenting', type_='foreignkey')
    op.drop_column('commenting', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commenting', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('commenting_user_id_fkey', 'commenting', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
