"""Fourth migration

Revision ID: 9b16cfd412f0
Revises: ca8c800249ea
Create Date: 2019-09-15 16:55:31.839637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b16cfd412f0'
down_revision = 'ca8c800249ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('content', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('users', 'question_text')
    op.drop_column('users', 'answer_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('answer_text', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('question_text', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'title')
    op.drop_column('users', 'content')
    # ### end Alembic commands ###
