"""Third migration

Revision ID: ca8c800249ea
Revises: e3f2c1f883f9
Create Date: 2019-09-15 13:52:50.781113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8c800249ea'
down_revision = 'e3f2c1f883f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('answer_text', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('question_text', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'question_text')
    op.drop_column('users', 'answer_text')
    # ### end Alembic commands ###
