"""init migration

Revision ID: deec06ec1cac
Revises: b2c2adc0abc2
Create Date: 2019-09-17 17:15:53.315407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deec06ec1cac'
down_revision = 'b2c2adc0abc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commenting', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'commenting', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commenting', type_='foreignkey')
    op.drop_column('commenting', 'user_id')
    # ### end Alembic commands ###
