"""init migration

Revision ID: fd2194ecea90
Revises: 11ccca6e3da8
Create Date: 2019-09-17 11:56:15.262260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2194ecea90'
down_revision = '11ccca6e3da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commenting', sa.Column('post_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'commenting', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commenting', type_='foreignkey')
    op.drop_column('commenting', 'post_id')
    # ### end Alembic commands ###
